--
-- PostgreSQL database dump
--

\restrict Qz0RkRF2fUwZiozOJNSgdZSh3K0F6cZxhVuvRvwLEQfUlBEo8sUd73C6k6vEqZB

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-10 19:29:35

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE challenge_acciones;
--
-- TOC entry 4984 (class 1262 OID 16388)
-- Name: challenge_acciones; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE challenge_acciones WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE challenge_acciones OWNER TO postgres;

\unrestrict Qz0RkRF2fUwZiozOJNSgdZSh3K0F6cZxhVuvRvwLEQfUlBEo8sUd73C6k6vEqZB
\connect challenge_acciones
\restrict Qz0RkRF2fUwZiozOJNSgdZSh3K0F6cZxhVuvRvwLEQfUlBEo8sUd73C6k6vEqZB

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 16404)
-- Name: favorite_stocks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorite_stocks (
    id integer NOT NULL,
    user_id integer NOT NULL,
    symbol character varying(16) NOT NULL,
    name character varying(255) NOT NULL,
    currency character varying(8) DEFAULT 'USD'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.favorite_stocks OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16403)
-- Name: favorite_stocks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.favorite_stocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_stocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    username character varying(64) NOT NULL,
    password_hash character varying(255) NOT NULL,
    display_name character varying(128) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4978 (class 0 OID 16404)
-- Dependencies: 222
-- Data for Name: favorite_stocks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.favorite_stocks (id, user_id, symbol, name, currency, created_at) FROM stdin;
2	1	NFLX	Netflix Inc	USD	2025-12-31 21:00:00-03
3	1	AAPL	Apple Inc	USD	2026-01-01 07:00:00-03
4	1	MSFT	Microsoft Corporation	USD	2026-01-01 08:00:00-03
5	2	AMZN	Amazon.com Inc	USD	2026-01-02 06:00:00-03
6	2	GOOGL	Alphabet Inc Class A	USD	2026-01-02 06:30:00-03
7	2	META	Meta Platforms Inc	USD	2026-01-02 07:00:00-03
8	3	NVDA	NVIDIA Corporation	USD	2026-01-03 05:00:00-03
9	3	AMD	Advanced Micro Devices Inc	USD	2026-01-03 05:30:00-03
10	3	INTC	Intel Corporation	USD	2026-01-03 06:00:00-03
11	4	JPM	JPMorgan Chase & Co	USD	2026-01-04 05:00:00-03
12	4	BAC	Bank of America Corp	USD	2026-01-04 05:30:00-03
13	4	V	Visa Inc	USD	2026-01-04 06:00:00-03
14	5	DIS	The Walt Disney Company	USD	2026-01-05 05:00:00-03
15	5	NKE	Nike Inc	USD	2026-01-05 05:30:00-03
16	5	KO	The Coca-Cola Company	USD	2026-01-05 06:00:00-03
17	5	PEP	PepsiCo Inc	USD	2026-01-05 06:30:00-03
18	1	AAP	Advance Auto Parts Inc.	USD	2026-09-10 18:48:39-03
\.


--
-- TOC entry 4976 (class 0 OID 16390)
-- Dependencies: 220
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, username, password_hash, display_name, created_at) FROM stdin;
1	demo	$2b$12$qFSxaCPJr6tlvI16ra52Z.TywRgHMRS4EWsJikjcz7F74jgWcify2	Usuario Demo	2025-12-31 21:00:00-03
2	ana	$2b$12$Rs5o6CQnCOR7hdmFkRIHvucKa4knldba8IHIe6oRsc32CkTDBpify	Ana Pérez	2026-01-01 21:00:00-03
3	bruno	$2b$12$jTUQR/zYh1/fP4LIjezwSOh/Yt4haHJu6E2VFxTYDwiWxO6KlFSyK	Bruno López	2026-01-02 21:00:00-03
4	carla	$2b$12$PO5/4WHZYzG/qiD2CVHJYeIfVFpZxlLE1FUBHraJq9Kf7iMC4OJNm	Carla Gómez	2026-01-03 21:00:00-03
5	diego	$2b$12$OI35oofxVj1Cz99b4d3UwuSKi4axZIqPOPivnvsO3.nNrxR7LT.R6	Diego Ruiz	2026-01-04 21:00:00-03
\.


--
-- TOC entry 4985 (class 0 OID 0)
-- Dependencies: 221
-- Name: favorite_stocks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.favorite_stocks_id_seq', 18, true);


--
-- TOC entry 4986 (class 0 OID 0)
-- Dependencies: 219
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 5, true);


--
-- TOC entry 4822 (class 2606 OID 16416)
-- Name: favorite_stocks favorite_stocks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_stocks
    ADD CONSTRAINT favorite_stocks_pkey PRIMARY KEY (id);


--
-- TOC entry 4826 (class 2606 OID 16418)
-- Name: favorite_stocks uq_favorite_stocks_user_symbol; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_stocks
    ADD CONSTRAINT uq_favorite_stocks_user_symbol UNIQUE (user_id, symbol);


--
-- TOC entry 4818 (class 2606 OID 16402)
-- Name: users uq_users_username; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uq_users_username UNIQUE (username);


--
-- TOC entry 4820 (class 2606 OID 16400)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4823 (class 1259 OID 16425)
-- Name: idx_favorite_stocks_symbol; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_favorite_stocks_symbol ON public.favorite_stocks USING btree (symbol);


--
-- TOC entry 4824 (class 1259 OID 16424)
-- Name: idx_favorite_stocks_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_favorite_stocks_user_id ON public.favorite_stocks USING btree (user_id);


--
-- TOC entry 4827 (class 2606 OID 16419)
-- Name: favorite_stocks favorite_stocks_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_stocks
    ADD CONSTRAINT favorite_stocks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


-- Completed on 2026-09-10 19:29:35

--
-- PostgreSQL database dump complete
--

\unrestrict Qz0RkRF2fUwZiozOJNSgdZSh3K0F6cZxhVuvRvwLEQfUlBEo8sUd73C6k6vEqZB

