-- Seed PostgreSQL desde backend/data/db.json
-- Uso: psql -U <user> -d <database> -f backend/data/seed_postgres.sql

BEGIN;

DROP TABLE IF EXISTS favorite_stocks CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)  NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    display_name    VARCHAR(128) NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE favorite_stocks (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    symbol          VARCHAR(16)  NOT NULL,
    name            VARCHAR(255) NOT NULL,
    currency        VARCHAR(8)   NOT NULL DEFAULT 'USD',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_favorite_stocks_user_symbol UNIQUE (user_id, symbol)
);

CREATE INDEX idx_favorite_stocks_user_id ON favorite_stocks (user_id);
CREATE INDEX idx_favorite_stocks_symbol ON favorite_stocks (symbol);

INSERT INTO users (id, username, password_hash, display_name, created_at) VALUES
    (1, 'demo',  '$2b$12$qFSxaCPJr6tlvI16ra52Z.TywRgHMRS4EWsJikjcz7F74jgWcify2', 'Usuario Demo', '2026-01-01T00:00:00Z'),
    (2, 'ana',   '$2b$12$Rs5o6CQnCOR7hdmFkRIHvucKa4knldba8IHIe6oRsc32CkTDBpify', 'Ana Pérez',    '2026-01-02T00:00:00Z'),
    (3, 'bruno', '$2b$12$jTUQR/zYh1/fP4LIjezwSOh/Yt4haHJu6E2VFxTYDwiWxO6KlFSyK', 'Bruno López',  '2026-01-03T00:00:00Z'),
    (4, 'carla', '$2b$12$PO5/4WHZYzG/qiD2CVHJYeIfVFpZxlLE1FUBHraJq9Kf7iMC4OJNm', 'Carla Gómez',  '2026-01-04T00:00:00Z'),
    (5, 'diego', '$2b$12$OI35oofxVj1Cz99b4d3UwuSKi4axZIqPOPivnvsO3.nNrxR7LT.R6', 'Diego Ruiz',   '2026-01-05T00:00:00Z');

INSERT INTO favorite_stocks (id, user_id, symbol, name, currency, created_at) VALUES
    (2,  1, 'NFLX',  'Netflix Inc',                 'USD', '2026-01-01T00:00:00Z'),
    (3,  1, 'AAPL',  'Apple Inc',                   'USD', '2026-01-01T10:00:00Z'),
    (4,  1, 'MSFT',  'Microsoft Corporation',       'USD', '2026-01-01T11:00:00Z'),
    (5,  2, 'AMZN',  'Amazon.com Inc',              'USD', '2026-01-02T09:00:00Z'),
    (6,  2, 'GOOGL', 'Alphabet Inc Class A',        'USD', '2026-01-02T09:30:00Z'),
    (7,  2, 'META',  'Meta Platforms Inc',          'USD', '2026-01-02T10:00:00Z'),
    (8,  3, 'NVDA',  'NVIDIA Corporation',          'USD', '2026-01-03T08:00:00Z'),
    (9,  3, 'AMD',   'Advanced Micro Devices Inc',  'USD', '2026-01-03T08:30:00Z'),
    (10, 3, 'INTC',  'Intel Corporation',           'USD', '2026-01-03T09:00:00Z'),
    (11, 4, 'JPM',   'JPMorgan Chase & Co',         'USD', '2026-01-04T08:00:00Z'),
    (12, 4, 'BAC',   'Bank of America Corp',        'USD', '2026-01-04T08:30:00Z'),
    (13, 4, 'V',     'Visa Inc',                    'USD', '2026-01-04T09:00:00Z'),
    (14, 5, 'DIS',   'The Walt Disney Company',     'USD', '2026-01-05T08:00:00Z'),
    (15, 5, 'NKE',   'Nike Inc',                    'USD', '2026-01-05T08:30:00Z'),
    (16, 5, 'KO',    'The Coca-Cola Company',       'USD', '2026-01-05T09:00:00Z'),
    (17, 5, 'PEP',   'PepsiCo Inc',                 'USD', '2026-01-05T09:30:00Z'),
    (18, 1, 'AAP',   'Advance Auto Parts Inc.',     'USD', '2026-09-10T21:48:39Z');

SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT MAX(id) FROM users));
SELECT setval(pg_get_serial_sequence('favorite_stocks', 'id'), (SELECT MAX(id) FROM favorite_stocks));

COMMIT;
